### ISSUE TITLE
Can't use creative tab because of a bug related to this mod

### ISSUE THREAD

**Issue by Sunconure11** [Tombenpotter/Sanguimancy#105]
http://pastebin.com/KzTnQnZz

Every time I try to use the creative tab in SMP, I crash with this error. But on singleplayer, I am fine.

**Comment by Sunconure11** [comment]
There was also this crash:

http://pastebin.com/6fgnuAVR

**Comment by retrozool** [comment]
I see similar in my logs over and over - even though I don't crash (I don't use creative), the log seems similar: 
[http://pastebin.com/2dfaT5Xr](http://pastebin.com/2dfaT5Xr)

It's really annoying as it spoils the logs so heavily. 
I'm guessing here but it could be an easy fix, assuming that stack.getItem() in onSanguimancyItemTooltip returns null, for whatever reason. So a null check for stack.getItem() could do the job - but again that's a wild guess :-)

**Comment by Tombenpotter** [comment]
I will look into this. I thought it had already been fixed, but eh. Expect a new version to go out if I manage to fix it :)

**Comment by xSable** [comment]
I am also experiencing this issue.

Thanks to some help on MC Forums, I learned that removing your mod from the server and client resolved the issue instantly. Not sure what's wrong, but I brought you a crash report in the hopes that it gets fixed.

On another note, this issue DID NOT OCCUR when clicked the search tab in creative mode while on SINGLEPLAYER. Only SMP. I don't know if that's the same for others, but the issue may be SMP related when it comes to the bug with your mod.

In my case, SMP is the only reoccurring issue. SSP is nothing. I can do singleplayer all day. For now I have to remove it from the server and modpack. Hope you fix it soon.

Crash Report:

http://pastebin.com/raw/9LnRGvr0

**Comment by retrozool** [comment]
Any news here?

**Comment by Tombenpotter** [comment]
Yeah, school got a bit hectic recently. I'll try to fix this this afternoon, and if not, by Thursday. Sorry about the delay!

**Comment by retrozool** [comment]
no worries - no need to hurry - school is always first ;-)
But great to hear that you may have a chance to fix that!

**Comment by retrozool** [comment]
Is there anything I can help you getting this fixed? I'm planning the next version of my pack and need to make a decision either to remove Sanguimancy or keep it, but therefor it needs to work properly.

**Comment by Tombenpotter** [comment]
I'm very sorry for that. I had looked at it, found the issue, fixed it (most probably) then forgot to release a new version. I'll verify everything is indeed fixed, and push a new version as soon as I get home (~15minutes). 

Sorry again!

**Comment by retrozool** [comment]
That's awesome to hear :) Will we get a new release (jar) or "only" the commit in GitHub?

**Comment by Tombenpotter** [comment]
A whole new release for you guys. It'll be on curse!

**Comment by Tombenpotter** [comment]
@retrozool The release is pending approval on curse. Keep me posted as to whether it worked or not!

**Comment by kindlich** [comment]
Still got the issue:

http://pastebin.com/XxkEwsim

Edit: I don't crash, it just keeps on spamming the log

**Comment by kindlich** [comment]
Update: I just tested a few versions, it happens from version #34 upwards, before that error doesnt occur in the log

**Comment by Mordenkainen** [comment]
I have seen a similar error happen if the ItemStack contains an invalid item or the Item is mis-registered so that it does not have a name registered. This causes the creation of the UniqueIdentifier to exception since it tries to call .split(":") on null. I have never been able to track it back to the actual item causing the issue.

Wrap the call to findUniqueIdentifierFor in a try/catch, that should make the log spam go away.

Note: Took a quick look at the WAILA code this was inspired by, and see it does indeed wrap the call in a try/catch: https://bitbucket.org/ProfMobius/waila/src/6b60705265ec7bb04eb4af2365253dec75cde53d/src/main/java/mcp/mobius/waila/utils/ModIdentification.java?at=forge_1580&fileviewer=file-view-default#ModIdentification.java-123

**Comment by Sunconure11** [comment]
I know 1.7.10 is probably not supported anymore, but I am still receiving this error.

http://pastebin.com/VzAieKNp

**Comment by xSable** [comment]
Issue still occuring today. 

Build 35
http://pastebin.com/jsNT2A6U

Build 34
http://pastebin.com/7tDwKZwS

Build 33
No Error. Creative tab works fine on server

Hopefully this helps finally solve this. Crash reports from both the updates, and knowing exactly which build doesn't have this error.

Maybe rollback the changes you made on just this part?

**Comment by MunkyMagick** [comment]
Still getting this issue too.
http://pastebin.com/TzpdN2y4

**Comment by xSable** [comment]
I've elected to keep using Build 33 for now. The updates in 34 and 35 are things I can live without, but as a server operator I can't go without creative for my builders.
