### ISSUE TITLE
Drill of the dead isn't working

### ISSUE THREAD

**Issue by Boter316** [Tombenpotter/Sanguimancy#108]
I don't know why, nor how to give you any data, but suddenly, the drill of the dead no longer works, i heard it required soul corruption, so I'm now 57 corrupt (so I can also make the crystals), and that changed nothing, then I heard it was 4 versions outdated so I updated it to 35, still nothing... please... help me mate... I've been going at it for 14 hours now... please get back to me on this

oh yeah, it takes the 50k life essence and consumes it but then does nothing
![2016-05-27_23 49 00](https://cloud.githubusercontent.com/assets/19333748/15625695/ac16f3be-2465-11e6-94d3-900f8478df0b.png)
![2016-05-27_23 49 06](https://cloud.githubusercontent.com/assets/19333748/15625696/ac1747e2-2465-11e6-8b76-9662fa42daef.png)

also after looking into the nbt I see it does the "runningTime" for about 100 ticks then stops
![2016-05-27_23 55 34](https://cloud.githubusercontent.com/assets/19333748/15625717/a8666d16-2466-11e6-864c-0db3cf255647.png)
during the "running time" which is about 5 seconds mind you, nothing happens then either

**Comment by TehNut** [comment]
Where is the altar?

**Comment by Boter316** [comment]
overworld, coordinates in the nbt

**Comment by TehNut** [comment]
The _altar_.

**Comment by Boter316** [comment]
no altar, didn't work with one before, so i didn't bother

**Comment by TehNut** [comment]
It only works with one...

**Comment by Boter316** [comment]
gimme like 15 minutes to reboot the pack

**Comment by Boter316** [comment]
wait, do you know if it works with the bloodarsenal compact blood altars?
or does it have to be the normal wayofflowingtime ones?

**Comment by TehNut** [comment]
I have never once launched Blood Arsenal.

**Comment by Boter316** [comment]
i'll try a normal one

**Comment by Boter316** [comment]
normal one works
i'll try blood arsenal now

**Comment by Boter316** [comment]
nope, drill of the dead does not accept the BloodArsenal:portable_altar as a altar

**Comment by TehNut** [comment]
Not a Sanguimancy issue, then.
