### ISSUE TITLE
[1.1.9-35] book text overflows pages and is offset

### ISSUE THREAD

**Issue by draeath** [Tombenpotter/Sanguimancy#110]
Rather than try to explain this one, it's best to just show it.

I'm seeing this behavior with "Sanguimancy-1.7.10-1.1.9-35.jar" - specifically as included in [VC3 1.4.1](https://www.atlauncher.com/pack/VaygrimsChance)

I am not using any resource packs that touch fonts, and am using the 'normal' GUI scale at 1920x1080.

![2016-06-09_0000](https://cloud.githubusercontent.com/assets/987449/15918516/5fbe4994-2dd5-11e6-9b83-1267f7d859f5.png)

**Comment by TehNut** [comment]
Downgrade your GuideAPI version by 1 build.

**Comment by draeath** [comment]
I have 1.0.1-29 - there is no -28 on Curse, only 1.0.1-23. Where can one get -28? Or are you meaning something else when you say build?

**Comment by TehNut** [comment]
Okay, 1 released version.

**Comment by draeath** [comment]
Appreciated!

.. OK, tried "Guide-API - 1.0.1-23" and that did _not_ solve the issue. Can I trouble you to be a bit more specific and call out a particular version/build?

I realize you won't be making any chances or, really, supporting 1.7.10 at all. I'm exceedingly grateful for any further time you spend on me, here :)

**Comment by TehNut** [comment]
I broke API in newer versions of GAPI for 1.7.10. Just keep downgrading until it's fine. I think 20 or 21 are what you're looking for.
