### ISSUE TITLE
Drill of the Dead won't activate.

### ISSUE THREAD

**Issue by zevric** [Tombenpotter/Sanguimancy#115]
I'm on the ATLauncher's Unabridged Pack and when i try to activate the Drill of the Dead it keeps telling me "You feel a pull but are too weak to push any further." I have over 2mil LP in my network and 4 Soul Corruption. Am I missing something to activate the ritual?

**Comment by TehNut** [comment]
Do you have the second tier of activation crystal?

**Comment by zevric** [comment]
Yeah but I forgot to bind it because I'm stupid. Thanks anyway man.
