### ISSUE TITLE
Server Crash during loading

### ISSUE THREAD

**Issue by CMCarlsen** [Tombenpotter/Sanguimancy#119]
Minecraft Version: 1.10.2
Forge version: 12.18.3.2185

This crash was specifically during the server launch, not client launch. I feel this is probably important? Large list of mods, so I won't list them here at the moment, but can if necessary (list will be contained in error report though).

Report here:
http://pastebin.com/Z3R4WbjR

Any questions, lemme know.

**Comment by TehNut** [comment]
Dammit, Tom

**Comment by Tombenpotter** [comment]
Erm whoops... I'll try to fix that ASAP :3

**Comment by Tombenpotter** [comment]
Alright, it's a good thing it wasn't too hard to fix. The fix is awaiting approval on curse :P

I'll close the issue once it gets approved

**Comment by Tombenpotter** [comment]
Version out! Go get it at https://minecraft.curseforge.com/projects/sanguimancy/files/2363165
