### ISSUE TITLE
[1.10.2] Client Crash due to Ticking Entity causing NPE

### ISSUE THREAD

**Issue by Morpheus1101** [Tombenpotter/Sanguimancy#120]
Crash Log @ https://puu.sh/t8uwx/152d0d9e6f.txt

**Comment by Tombenpotter** [comment]
I won't be home until tonight, but does this happen only sometimes, or can you play and then happen to crash sometimes?

**Comment by Morpheus1101** [comment]
This happens instantly when trying to join a world.

Im just running tests atm, it'll be few more days or more b4 it'll possibly be on MMD

**Comment by Tombenpotter** [comment]
Well shit. I'm sorry, I can't take a look before this evening though

**Comment by Tombenpotter** [comment]
Fixed as of https://minecraft.curseforge.com/projects/sanguimancy/files/2363460
