### ISSUE TITLE
Bug:  Sanguimancy update check spamming chat

### ISSUE THREAD

**Issue by Kaisoul** [Tombenpotter/Sanguimancy#121]
minecraft 1.10.2
forge-1.10.2-12.18.3.2202
Sanguimancy-1.10.2-2.0.2

you login, sleep, & change dimensions the chat will be spammed with a you are up to date message.

**Comment by Tombenpotter** [comment]
...will fix. Makes very little sense that this would happen though, but eh :P

**Comment by Tombenpotter** [comment]
Fixed. You don't even have to update the mod. Could you confirm it's fixed?

**Comment by Kaisoul** [comment]
will test in a few gotta go find something to wake me up...blasted
narcolepsy

**Comment by Kaisoul** [comment]
loaded up my world and have zero spam now

**Comment by Tombenpotter** [comment]
Perfect!
