### ISSUE TITLE
[1.7.10] Crash on rendering GUI

### ISSUE THREAD

**Issue by Diamssword** [Tombenpotter/Sanguimancy#129]
Hi, I'm building a modded server, crash occure when I click on the search tab in the creative inventory.
It crash only on muktiplayer, on singleplayer, it work fine.

[crash-2017-05-20_09.38.21-client.txt](https://github.com/Tombenpotter/Sanguimancy/files/1015994/crash-2017-05-20_09.38.21-client.txt)

Can you, please, help me? 
Thanks!

**Comment by TehNut** [comment]
#105
