### ISSUE TITLE
[1.7.10] Blood tanks lose entity data, causes world corruption

### ISSUE THREAD

**Issue by cjriches** [Tombenpotter/Sanguimancy#130]
A tier one blood tank was used to store Liquid Etherium from Ars Magica 2. It was subsequently stored in a chest for a while.

Now, it seems to be corrupted; when in the chest all is fine, but as soon as it is placed in the world, it corrupts that entire chunk. I was unable to reproduce the bug with new tanks, regardless of contents, and eventually whilst exploring with MCedit I found the problem. The new tank, spawned in via NEI, has a TileEntity associated with it when placed. The corrupt tank does not; it is simply a plain block with the blood tank ID.

I have no idea how the tank lost this data, but the lack of data and subsequent corruption happens every time **that specific tank** is placed.

I have attached a link for the relevant world in two states: with the offending tank in a chest near the player, and with the offending tank placed (which can only be opened by MCedit, will case Minecraft to crash). Also attached is the crash log, and screenshots showing the difference in TileEntity data. There is nothing relevant in the client log as far as I can tell.

I hope this bug can be fixed in the 1.7.10 version, as it is ruining my current modded playthrough.

(NOTE: the world may not make much sense without Thaumcraft, but should still load with missing blocks. It will be almost certainly necessary to install Ars Magica 2 to load the world as the tanks contain Liquid Etherium).
Link: https://www.dropbox.com/s/pftw1889d5lrhea/BloodTankCrashData.zip?dl=1

**Comment by TehNut** [comment]
Sorry, 1.7.10 is no longer supported.

**Comment by cjriches** [comment]
Is this/will this be fixed in the latest 1.10 version?

**Comment by TehNut** [comment]
Well they're implemented directly in Blood Magic and it doesn't happen, soooo...
