### ISSUE TITLE
[1.7.10] Problem creating flat world

### ISSUE THREAD

**Issue by kutschkem** [Tombenpotter/Sanguimancy#131]
Creating a flat world produces the following error:

The game crashed whilst exception getting block type in world Error: java.lang.ClassCastException: tombenpotter.sanguimancy.world.ChunkProviderSNDimension cannot be cast to net.minecraft.world.gen.ChunkProviderFlat

Seed of the world is -4928730477948321385

**Comment by kutschkem** [comment]
Other seeds work, too. It happens in conjunction with Chromaticraft worldgen on flat worlds enabled.

**Comment by TehNut** [comment]
1.7.10 is no longer supported.
