### ISSUE TITLE
Recipes out-of-bounds in book

### ISSUE THREAD

**Issue by ubermentat** [Tombenpotter/Sanguimancy#22]
System: Mac OS 10.10.1
Client: MultiMC 0.4.5
Forge: 1277
Sanguimancy Version: 1.1.9 Pre-10

When reading the book, images are displaced above the actual boundaries of the page, as seen in the images below. Additionally, some images render on top of a missing-textures background, although I am unsure as to what is supposed to be rendered there.

![2015-01-14_17 02 34](https://cloud.githubusercontent.com/assets/5168763/5749360/389e1d28-9c16-11e4-88c8-31639370c37a.png)
![2015-01-14_17 03 29](https://cloud.githubusercontent.com/assets/5168763/5749361/38a02550-9c16-11e4-9536-9ff03bfd5207.png)
![2015-01-14_17 03 48](https://cloud.githubusercontent.com/assets/5168763/5749362/38a0a26e-9c16-11e4-8ea5-926a76fedfc2.png)
![2015-01-14_17 06 02](https://cloud.githubusercontent.com/assets/5168763/5749363/38a37fb6-9c16-11e4-957c-3fbea307545e.png)

**Comment by TehNut** [comment]
It's still *very* WIP. Hell, I'd prefer to use a different API for the books.

**Comment by ubermentat** [comment]
Would it be possible to use a setup similar to Enchiridion? Obviously I wouldn't recommend just using it outright, since it would be yet another dependency. That said, Enchiridion books are just compressed xml files, which might make them easier to format.

**Comment by TehNut** [comment]
No offense to Waslie, but *anything* other than this would be nice, honestly. However that is all up to Tom.

**Comment by Tombenpotter** [comment]
Honestly, when I tested the book, I didn't have that many issues...
If there are any book APIs out there that are less buggy, I'll probably change and use those. But the thing is, I don't know if there are any out there.=

**Comment by ubermentat** [comment]
The only ones I know of are Enchiridion and whatever Tinkers' Construct uses, but I think either of those would create extra dependencies.

**Comment by Tombenpotter** [comment]
I went for the hard way! I'm going to try and make my own system. Hopefully I don't horribly fail.

**Comment by Timeslice42** [comment]
The book only formats correctly if you have your GUI scale set to 'auto'.

**Comment by Tombenpotter** [comment]
Fixed with the moving over to Guide-API
