### ISSUE TITLE
[Suggestion] Configs for Soul Network Dimension

### ISSUE THREAD

**Issue by FakoTheGreat** [Tombenpotter/Sanguimancy#23]
Considering the new config option for auto-claiming chunks in the Soul Network Dimension, it would be nice to have configs to prevent the blocks from being moved around, for packs not designed for PvP.

Also, it would be cool if the owner of the block could move the blocks within their chunk to allow for sorting of their network (granted, teleposers, but if disabled via config...)

**Comment by Tombenpotter** [comment]
Working on it!

**Comment by Tombenpotter** [comment]
BM has no teleposer blacklist. Yet. I'll work on that when the blacklist is implemented.

**Comment by TehNut** [comment]
@Tombenpotter There is an event for Teleposing that you can cancel, now. As of https://github.com/WayofTime/BloodMagic/commit/e32744f3b3d12b59411977f6c526e98a42054d28

**Comment by Tombenpotter** [comment]
Done half of it as of 050f693cbe1363815b820ffa14d08acba7b76faf
