### ISSUE TITLE
Glitch with Steve's Factory Manager

### ISSUE THREAD

**Issue by ArcaneTechnician** [Tombenpotter/Sanguimancy#24]
With Sanguimancy installed, whenever a player tries to modify a whitelist or blacklist in the factory manager, the client crashes. It seems to revolve around an item (ItemOreLump) not allowing the screen to update. I'm not sure if it is a bug with said item or if it has to do with Factory Manager, but I thought I would check in case this is something you could fix.

**Comment by Tombenpotter** [comment]
That's strange. I'll see what I can do.

**Comment by Tombenpotter** [comment]
I don't understand what could be causing the crash. As far as I've seen, and from the crash report that was given to me on my forum thread, the crashlog points to a line where I.. cut a string. I'll try to do it in an other way, but I've got no guarantee whatsoever that it'll work.

**Comment by ArcaneTechnician** [comment]
Thank you for trying, this has been one of the mods I've been dying to try out, and think it will be one of my favorites.

**Comment by Tombenpotter** [comment]
Should be fixed. Tell me if it isn't, the issue won't get closed until I get your confirmation :)

**Comment by Tombenpotter** [comment]
I consider this fixed. Open another issue if it is not.

**Comment by ArcaneTechnician** [comment]
Sorry, but the glitch seems to be fixed, thank you so much. (I haven't been online much, and missed your comment.)
