### ISSUE TITLE
Crash When Placing the Soul Transfer thing

### ISSUE THREAD

**Issue by HaroldDaFrog** [Tombenpotter/Sanguimancy#26]
When placing the thing that lets me eat someone's lp, I got this crash - 
http://pastebin.com/XEsFswdP

**Comment by Tombenpotter** [comment]
Dude, be a bit more precise :P. 
Can you tell me exactly what happened? Placing the block in the world or putting the sacrificing stone in it?

**Comment by HaroldDaFrog** [comment]
Whoops sorry, wrote that up real quick while restarting my client. When I placed the soul transfer block on the ground next to a ztones block, I immediately got that crash. I couldn't log back in to the server until Fako mcedit'ed out the floor near me.

**Comment by Tombenpotter** [comment]
I've not been able to reproduce that. I consider it as a rogue crash. Reopen an issue if it happens again.
