### ISSUE TITLE
[Suggestion] Altar Diviner should consider the items already in the altar.

### ISSUE THREAD

**Issue by Exadi** [Tombenpotter/Sanguimancy#27]
The simplest way would be don't put more stuff in if something's already in there, but if you want to go crazy with it you could maybe do something like if there's 1 stone in there and it's 50% infused it will require 1500 LP in the altar to put in the 1 stone it has.

**Comment by Tombenpotter** [comment]
Should be fixed in 9757339d0e11f1bd45870d65e54878a346562425
New build will be on the Jenkins in a few minutes
