### ISSUE TITLE
Crash using Steve's Factory Manager

### ISSUE THREAD

**Issue by benten2000** [Tombenpotter/Sanguimancy#28]
I saw the closed issue about the same error I am still getting when using the Steve's Factory Manager.

When using the Inventory Manager block and in the Item box where you type the name of the item you want soon as I press one letter the game crashes.

Using latest of both Sanguimancy & Factory Manager

Here is the crash report to hopefully help track down the problem.
http://pastebin.com/XCTpuK9B

**Comment by TehNut** [comment]
That is not the latest version. [This](http://tehnut.info/jenkins/job/Sanguimancy/19/) is.

**Comment by benten2000** [comment]
Well latest [stable] then :)
Shall give that a quick try then

**Comment by Tombenpotter** [comment]
Haha. Stable? I NEVER release anything that's not a least decently stable.

**Comment by TehNut** [comment]
^

**Comment by Tombenpotter** [comment]
Since no response was given, I consider this closed. Open another issue if it still happens.
