### ISSUE TITLE
Multiple IO exceptions each time client & server start

### ISSUE THREAD

**Issue by Morpheus1101** [Tombenpotter/Sanguimancy#32]
http://pastebin.com/J534T8JB

**Comment by Tombenpotter** [comment]
Does it crash the game or is it simply some console output [spam]?

**Comment by Morpheus1101** [comment]
Its console output, no crash, but (for me) it does slow the loading of the game down an it isnt a 1 off message that ocurs

**Comment by Tombenpotter** [comment]
Don't worry I was not trying to tell you to ignore this. I was just trying to figure out what it was.

**Comment by Morpheus1101** [comment]
All good :D

**Comment by Tombenpotter** [comment]
I still haven't been able to reproduce this.. sorry :/

**Comment by Morpheus1101** [comment]
Id forgotten about this one .. After looking through logs im not seeing the msg i 1st posted occuring anymore, so for now id say what ever it was has been fixed or resolved itself, appreciate the time in looking into it.
