### ISSUE TITLE
Removehearts II being applied to the bound armor

### ISSUE THREAD

**Issue by misterfixit** [Tombenpotter/Sanguimancy#33]
When applying the sigil of haste to the bound armor, along with a master blood orb and a demon shard, the haste effect of the sigil is being overwritten by the removehearts II effect.

**Comment by itsmehor** [comment]
Can confirm, having same issue.

**Comment by itsmehor** [comment]
to clarify, the Boost buff was replaced. the fast miner sigil is still working. but the sigil of haste is giving removeheart2 buff as well.

**Comment by itsmehor** [comment]
Did some more testing, can't even use sigil of haste by itself.

**Comment by Tombenpotter** [comment]
This is not a Sanguimancy issue. It's simply a potions id conflict.

**Comment by itsmehor** [comment]
^thanks for the response.

**Comment by misterfixit** [comment]
are your potion ids static?

**Comment by TehNut** [comment]
If you mean "Can you change them?", then yes. https://github.com/Tombenpotter/Sanguimancy/blob/TestProbablyBroken/src/main/java/tombenpotter/sanguimancy/util/ConfigHandler.java#L65-L66
