### ISSUE TITLE
Blood Interface recipe is... broken

### ISSUE THREAD

**Issue by Timeslice42** [Tombenpotter/Sanguimancy#36]
The blood interface recipe is using minecraft:fire as it's center component, which is uncraftable through vanilla means. Co-incidentally, trying to render the fire block crashes the (wasliecore) book API.

**Comment by TehNut** [comment]
@Tombenpotter Why haven't you removed that stupid old book, yet?

**Comment by Tombenpotter** [comment]
Hey I'm doing it soon! I modified the build.gradle to start yesterday, but I fell asleep on my keyboard.. I'll do it today :P

**Comment by Tombenpotter** [comment]
Fixed, and moved over to Guide-API

**Comment by Timeslice42** [comment]
But is the recipe fixed?
