### ISSUE TITLE
The Ritual of Enlightenment is broken

### ISSUE THREAD

**Issue by Timeslice42** [Tombenpotter/Sanguimancy#37]
I believe the Ritual of Enlightenment isn't being properly registered, as the ritual diviner refuses to place any blocks for it. I can't quite make out the ritual stones in the screenshot, so I can't really test to see if the ritual is working at all.

**Comment by Tombenpotter** [comment]
You should check your config. There is no reason for this to happen

**Comment by Tombenpotter** [comment]
Oops :p

**Comment by Timeslice42** [comment]
You mean is the ritual set to true? Yes, they're all set to true.

**Comment by Tombenpotter** [comment]
I've just had a thought.. the fact that the ritual diviner refuses to place blocks for it simply means there are other blocks in the place where rituals stones would go. Typically, this ritual needs the master stone to float with 1 layer of air under it

**Comment by Timeslice42** [comment]
Well, dangit. It never occured to me that it might be trying to place stones *under* the master ritual stone. I wish the ritual diviner would display ghost blocks of where it's trying to place, or something, so that we could avoid silly mistakes like that.

Do you think, maybe, that you could put a more close-up screenshot of the enlightenment ritual on the thread post (like imgur.com/UQwoA3D)? And/or a note in the manual?

**Comment by TehNut** [comment]
The manual is being rewritten currently. I'm going to probably going to take new screenshots for it.

toms pikturz r bad 'n he shud fel bad
