### ISSUE TITLE
Corrupted shaped recipe [Harcore Ender Expansion]

### ISSUE THREAD

**Issue by DeForce** [Tombenpotter/Sanguimancy#39]
Good day,

http://pastebin.com/cxqUHSPM
As per HEE crash report, and wiki thread I'm here to report that issue.

The issued recipe is:
http://pastebin.com/chgHBEWd

Best Regards,
DeForce

**Comment by Tombenpotter** [comment]
Thank you for reporting this. I'll take a look at it when I get back home.

**Comment by Vekseid** [comment]
Getting this also.

**Comment by Tombenpotter** [comment]
Obviously. I'll probably be fixing this during the weekend.

**Comment by Tombenpotter** [comment]
Fixed.
