### ISSUE TITLE
Crash after 200+ soul corruption.

### ISSUE THREAD

**Issue by DeForce** [Tombenpotter/Sanguimancy#41]
Good Day,

So I have spammed activating drill of the dead and I got 200 corruption. I got the "funny" effects as random cobble and stone on the ground and random block appearing right beside me and chickens.
But after I got 200 corruption I get "hit" sound and my game crashes. 
Pastebin: http://pastebin.com/zwDq0KWb

For now I can play for like 30 seconds and my game crashes again....

People on servers said that "...misplaced a couple of hearts" happened.

Best Regards,
DeForce

**Comment by Tombenpotter** [comment]
I do not believe this is my fault. Nowhere in the log does it link to mod, as least as far as a quick read showed. The issue seems linked to a potion, so I advise you to get rid of your potion effects in you player.dat

**Comment by Tombenpotter** [comment]
I still don't have any confirmation of this. Closing it.
