### ISSUE TITLE
Too many chickens

### ISSUE THREAD

**Issue by OldOpa** [Tombenpotter/Sanguimancy#48]
It would be good if there don't spawn too much minion chickens since they will stack up if afk. Or otherwise that they will despawn (kill without drops) after a given times (couple minutes).
If you look closely there are multiple chickens stacked into each other. They don't move, pushed and cannot be hurt. I think it happens if the player is standing still.
![2015-05-04_09 53 50](https://cloud.githubusercontent.com/assets/10256143/7450309/b7615ee4-f243-11e4-88f4-b854863f8a43.png)

**Comment by Tombenpotter** [comment]
I will make them disappear after a couple of minutes. Or more actually
