### ISSUE TITLE
Teleport into blocks

### ISSUE THREAD

**Issue by OldOpa** [Tombenpotter/Sanguimancy#49]
You can teleport into blocks when the random teleporting happens due to "higher forces". Maybe check for air blocks or use enderman-teleporting (net.minecraft.entity.monster, line 274ff)
https://github.com/Tombenpotter/Sanguimancy/blob/b803cdb396d4db9bfddaa25a6243f545fc3cde1a/src/main/java/tombenpotter/sanguimancy/api/soulCorruption/SoulCorruptionHelper.java#L94

**Comment by Tombenpotter** [comment]
This is not a bug.
