### ISSUE TITLE
Licence mistake ?

### ISSUE THREAD

**Issue by Goju-Sulfam** [Tombenpotter/Sanguimancy#50]
Curse/Curse Forge say your mod is under the "GNU GPL V3 License", but on this github it is under the Creative Commons Attribution 4.0 International License.

It's a bit confusing when you try to make a modpack. I am supposed to mark this mod under GPL or CC 4 ?

(sorry if this post is not grammatically perfect, English is not my native language)

**Comment by Tombenpotter** [comment]
Listen to the github. I derped on Curse :p

**Comment by Tombenpotter** [comment]
Oh, I remember. CC4 isn't available on curse. That's why!

**Comment by Tombenpotter** [comment]
Fixed anyways.
