### ISSUE TITLE
GuideAPI/Sanguimancy crash

### ISSUE THREAD

**Issue by whitestarx0312** [Tombenpotter/Sanguimancy#52]
Upon opening the GuideAPI book, I get this Sanguimancy crash.

Forge: forge-10.13.3.1387
GuideAPI: Guide-API-1.7.10-1.0-13
Sanguimancy: Sanguimancy-1.7.10-1.1.9-29
Bloodmagic: BloodMagic-1.7.10-1.3.2-1
Agrarian Skies: 1.0.39

Log: http://pastebin.com/346h8rb0
*Log is too big for pastebin, let me know if you need the full one.
*I am using Optifine and Fastcraft.

**Comment by Tombenpotter** [comment]
I wasn't aware of this issue exactly, but there have been problems with Soul Corruption in general. I will fix this

**Comment by whitestarx0312** [comment]
sweet!
