### ISSUE TITLE
Chicken config

### ISSUE THREAD

**Issue by WolfieWaffle** [Tombenpotter/Sanguimancy#57]
The chickens are extremely annoying and I can't find the purpose of them. Other people on the forum also mentioned the chickens being annoying. So I think either an explanation of what they are or a config option to disable them would be helpful.

**Comment by TehNut** [comment]
They are one of the downsides to gaining lots of corruption.

**Comment by WolfieWaffle** [comment]
OK, they just appear too much and seems to glitch - sometimes they just stand there and you can't hurt them. Also is the chicken message global? Because that get annoying if other players keep seeing the message, especially if multiple players are corrupted.

**Comment by TehNut** [comment]
>is the chicken message global? 

As of 4a176ba27b6ba421337cf1d227b5d62599be2436 that is a config.

**Comment by WolfieWaffle** [comment]
Cool :)
