### ISSUE TITLE
Exception while updating neighbours

### ISSUE THREAD

**Issue by GodNero** [Tombenpotter/Sanguimancy#61]
Minecraft - 1.7.10
--------Involved Mods------
Ender IO - 2.2.8.381
Sanguimancy - 1.1.9-29
Mekinism - 8.1.3.231
--------Crash Report-------
Pastebin - http://pastebin.com/menKawd7

I can't tell you what was going on before this crash happened as this is from one of the servers using the Resonant Rise pack. I am still trying to recreate this issue, just thought you might have some insight on this one.

---------------------
Mekanism - https://github.com/aidancbrady/Mekanism/issues/2720
Ender IO - https://github.com/SleepyTrousers/EnderIO/issues/2543

**Comment by Tombenpotter** [comment]
This doesn't make much sense, but I added a couple of checks that should be able to prevent this from happening

**Comment by Tombenpotter** [comment]
I am waiting for confirmation before closing this issue.

**Comment by GodNero** [comment]
Thanks, Sorry I was unable to give any more information that what was given to me. I was still unable to reproduce the error to help confirm.
