### ISSUE TITLE
Importing classes

### ISSUE THREAD

**Issue by ugrashrath** [Tombenpotter/Sanguimancy#62]
Original issue posted on: http://minecraft.curseforge.com/modpacks/225550-agrarian-skies-2/issues/940

sanguimancy/util/RitualUtils.java

is importing "WayofTime.alchemicalWizardry.common.Int3" which has been moved to "WayofTime.alchemicalWizardry.api.Int3"

and is crashing since the class isn't importing correctly.

I would also suggest adding in a check to see if the classes exist when doing cross-mod integration.

**Comment by TehNut** [comment]
>I would also suggest adding in a check to see if the classes exist when doing cross-mod integration.

You generally don't do that when your mod is a direct addon. Meaning it's not integration, it's... you know... the mod.

**Comment by ugrashrath** [comment]
True. It would have prevented that kind of crash though. Up to you.

**Comment by TehNut** [comment]
It's just that Tom hasn't updated his local BM dep. There's absolutely no need to check classes...

**Comment by Tombenpotter** [comment]
It would have prevented it. But I'm not about to check every single method I use from BM :P
