### ISSUE TITLE
Cannot Create Worlds after updating Guide API / Sanguimancy / Blood Magic; mod conflict, clean install works.

### ISSUE THREAD

**Issue by renadi** [Tombenpotter/Sanguimancy#63]
I have a custom pack that had Sanguimancy in it, after updating something very odd happens, anytime I try to create/join a world it does the normal stuff, says converting world, building terrain, etc... and then goes to the main menu.

The really worrying thing is when closing the launcher after this there's a java application open taking up about 2GB of ram that I have to force close.

removing Sanguimancy fixes the issue, but no error occurs in a setup involving only guide api blood magic and sanguimancy, so I'm not even sure it's on your end, but this is as much information as I really know how to gather on it.

Paste is after force closing java.

http://pastebin.com/Fu6caayC

**Comment by TehNut** [comment]
#55 #56 #58 #59 
Refresh your config.
