### ISSUE TITLE
Crash When Reading Through DID book

### ISSUE THREAD

**Issue by MtnDrew** [Tombenpotter/Sanguimancy#64]
Specifically when opening up the page for Player Sacrificing Stones, it will open to the first page, but if I turn to the page after that, I get this crash: http://pastebin.com/we3JRcxw.

I am using the newest Guide API, since Blood Magic added it's own book.

**Comment by TehNut** [comment]
Could you maybe provide some actually useful information?

**Comment by MtnDrew** [comment]
That was my bad I accidentally hit the post button before I finished.

**Comment by TehNut** [comment]
That would be because Tom has yet to fix his pages to implement `IRecipeRenderer` instead of extending `PageIRecipe`. He should have fixed this when I yelled at Way for doing it. >.>

**Comment by Tombenpotter** [comment]
I was bizy. I'll fix all that tonight.
