### ISSUE TITLE
Crash at Startup, both server and client

### ISSUE THREAD

**Issue by digger5** [Tombenpotter/Sanguimancy#67]
Hi. 
When i try to install Sanguimancy-1.7.10-1.1.9-31 i receive a crash to desktop right before the main menu screen.

Crashlog: http://pastebin.com/40zS40NQ

I hope someone can tell me if i do something wrong or if this is a bug.

**Comment by Tombenpotter** [comment]
Update your BM to -4

**Comment by digger5** [comment]
Thanks, 
that solved this.
close this now
