### ISSUE TITLE
"There was a severe problem during mod loading that has caused the game to fail"

### ISSUE THREAD

**Issue by Yowesephth** [Tombenpotter/Sanguimancy#68]
Only happens when I try to load sanguimancy
http://pastebin.com/4VKHd2Ac

**Comment by Tombenpotter** [comment]
Update your Blood Magic to -4

**Comment by Yowesephth** [comment]
Updated blood magic, still having the same issue
http://pastebin.com/qb0SQyjd

**Comment by Tombenpotter** [comment]
Update Guide-API this time :p
