### ISSUE TITLE
soul transporter?

### ISSUE THREAD

**Issue by Turmfalke2** [Tombenpotter/Sanguimancy#70]
hi,
I have no idea what the soul transporter is supposed to do, but at least it threw an exception while doing what it did.
I crafted one, right clicked it and it dropped me in a void world with a bedrock floor. Is this supposed to happen? The soul transporter also disappeared when I did that.

error: http://pastebin.com/zccfC2Y4

Edit:
when looking up the soul transporter in the book the game crashed: http://pastebin.com/nU5McuDb

**Comment by Tombenpotter** [comment]
Did you read the guide entry for the Soul Transporter? I think not.

**Comment by Turmfalke2** [comment]
As I said.. when I try to read it the game crashes.

**Comment by Tombenpotter** [comment]
As I cannot seem to find guide API in your modlist, I suggest you try and get the latest version.  I am not home so this is just a quick read of your crash log.  I will see what is wrong tomorrow.

**Comment by Turmfalke2** [comment]
Guide-API-1.7.10-1.0.1-20.jar

**Comment by Tombenpotter** [comment]
I am also unable to find what version of Sanguimancy you are using.

**Comment by Turmfalke2** [comment]
Sanguimancy-1.7.10-1.1.9-30.jar

**Comment by TehNut** [comment]
Why not try the latest version then?

**Comment by Tombenpotter** [comment]
^
