### ISSUE TITLE
timberman ritual crashes

### ISSUE THREAD

**Issue by Turmfalke2** [Tombenpotter/Sanguimancy#72]
hi,
I created a ritual of the timberman, activated it and placed a chest on top of it, now when ever I load into the world it directly crashes me.
http://pastebin.com/rw9htk50

Sanguimancy-1.7.10-1.1.9-30.jar
BloodMagic-1.7.10-1.3.3-4.jar

**Comment by TehNut** [comment]
>Sanguimancy-1.7.10-1.1.9-30.jar

**Comment by Tombenpotter** [comment]
Comtes back and report bugs once you've updated.

**Comment by Turmfalke2** [comment]
updated, couldn't reproduce

**Comment by Tombenpotter** [comment]
Of course you couldn't reproduce it, it was fixed.

**Comment by Turmfalke2** [comment]
well, your changelog is not exactly what I would call helpful

**Comment by Tombenpotter** [comment]
Changelog is automatically generated from the commit names. I do not control it.

**Comment by Turmfalke2** [comment]
I was referring to the changelog linked in your forum post.
https://github.com/Tombenpotter/Sanguimancy/blob/master/Changelog.txt
