### ISSUE TITLE
ArrayIndexOutofBounds Exception 

### ISSUE THREAD

**Issue by cauliflower69** [Tombenpotter/Sanguimancy#74]
https://paste.ee/p/8QRJW

Just updated our private pack and we are crashing on startup

**Comment by cauliflower69** [comment]
Downgrading to a lower version of your mod, fixes the issue

**Comment by Tombenpotter** [comment]
So does deleting the config file. I should really put that somewhere :p

**Comment by cauliflower69** [comment]
Thanks for the feedback
