### ISSUE TITLE
Ethereal Blocks interact with a Wither in strange ways

### ISSUE THREAD

**Issue by Timeslice42** [Tombenpotter/Sanguimancy#75]
When an ethereal block is hit by the wither's blue skull attack the block is dropped as an item (as if it was broken), but the block remains in place, essentially duping the block.

Also the Wither is able to straight up destroy personal ethereal blocks in melee/by flying into them.

**Comment by MyDeloreanWontStart** [comment]
/me makes an ethereal block dupe farm


Actually though, this sounds like an issue with the block break not registering since ethereal blocks are made with custom code that tells it not to break for anything, but with no damage level. Idk, just my theory.

**Comment by Tombenpotter** [comment]
Well, I'll have a shot at fixing all the issues once the heat wave passes, and I am able to turn on my computer without frying half of its components :D

**Comment by MyDeloreanWontStart** [comment]
France, eh? By the way, how bad is it? I'm going to be there on Tuesday, so tell me what I'm dealing with... :-D Good luck though.

**Comment by Tombenpotter** [comment]
The worst has passed, don't worry. But we went up to 40-41C :P

**Comment by MyDeloreanWontStart** [comment]
Huh, good luck with the heat and the code :-P

**Comment by Timeslice42** [comment]
Wow, that's retarded hot. We're having a heat wave here in Oregon, but that's only putting us in the mid-high 90's F. Makes me glad we have an extra air conditioner in the computer room.

**Comment by MyDeloreanWontStart** [comment]
Being in paris now, its not too bad, but judgement is still reserved. ;-)
