### ISSUE TITLE
Drill of dead Blood use

### ISSUE THREAD

**Issue by EthricTheMage99** [Tombenpotter/Sanguimancy#77]
The drill of the dead claims to take 75 LP per kill but instead it does 75 LP per tick the ritual is active. Also I would like to ask if the drill of the dead ritual works with sacrificial stones.

**Comment by Tombenpotter** [comment]
It does. And I'm not sure about the LP per tick, but it shouldn't be so. And I'm sorry, we're in December and you posted this in July <.>

**Comment by darthcheddar** [comment]
Tomben, take a look at  performEffect in Drill of the dead. Particularly line 83: SoulNetworkHandler.syphonFromNetwork(owner, getCostPerRefresh()). 

You do not multiple by the number of entities. So you don't take 75L _per_ entity. And when there are 0 entities, you still take 75LP.

**Comment by TehNut** [comment]
https://github.com/Tombenpotter/Sanguimancy/blob/TestProbablyBroken/src/main/java/tombenpotter/sanguimancy/rituals/RitualEffectDrillOfTheDead.java#L83
