### ISSUE TITLE
Suggestion: Altar Diviner inputs as much as is possible

### ISSUE THREAD

**Issue by drz2k** [Tombenpotter/Sanguimancy#84]
Hi,

im currently playing around with the Diviner and its great. Only thing i found a bit lacking is that with full automation you can get into a stall situation.

E.g. diviner has a full stack and the amount of LP needed are over the altars limit. Would be great if the diviner could just insert the maximum amount that is possible with the LP.

**Comment by Tombenpotter** [comment]
Get the Altar Manipulator. The Altar Diviner is meant not to be perfect. :P

From: drz2k 
Sent: Monday, September 07, 2015 4:13 PM
To: Tombenpotter/Sanguimancy 
Subject: [Sanguimancy] Suggestion: Altar Diviner inputs as much as is possible (#84)

Hi,

im currently playing around with the Diviner and its great. Only thing i found a bit lacking is that with full automation you can get into a stall situation.

E.g. diviner has a full stack and the amount of LP needed are over the altars limit. Would be great if the diviner could just insert the maximum amount that is possible with the LP.

**Comment by drz2k** [comment]
Well yes, but its not really cheap. Solved this on my modpack by putting translocators in ;)
