### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Zsashas** [Tombenpotter/Sanguimancy#90]
It happens at seemingly random times, but causes lag spikes every time it happens, which is frequently.

[NEI Item Filtering/INFO] [Sanguimancy/]: No mod found for this item
[NEI Item Filtering/INFO] [Sanguimancy/]: No mod found for this item
[NEI Item Filtering/INFO] [Sanguimancy/]: No mod found for this item

**Comment by Iarinu** [comment]
Same here with the same version
Seems like it's allways happening when I am searching "tank" in NEI
