### ISSUE TITLE
Factorization interaction???

### ISSUE THREAD

**Issue by Zsashas** [Tombenpotter/Sanguimancy#94]
Steps to reproduce:
Place a Factorization Hinge.
Place a block on the moving side of the hinge.
The message "This was dropped when your Soul formed." appears in the chat. It happens every time I place a block on the hinge, if it is the first block on the hinge. Breaking and replacing the hinge allows it to happen again. The Soul Chunk Claimer does not actually appear every time, only the chat message.

Factorization doesn't appear to have an issue tracker so...

**Comment by TehNut** [comment]
The only way for that code to run is if an EntityPlayer joins the world.

https://github.com/Tombenpotter/Sanguimancy/blob/master/src/main/java/tombenpotter/sanguimancy/util/EventHandler.java#L108

This is most likely a Factorization issue.
